export const provinces: Record<
  string,
  {
    key: string;
    name_la?: string;
    name_en?: string;
    districts_la: string[];
    districts_en: string[];
  }
> = {
  Attapeu: {
    key: "Attapeu",
    name_la: "ອັດຕະປື",
    name_en: "Attapeu",
    districts_la: ["ໄຊເຊດຖາ", "ສາມັກຄືໄຊ", "ສະໜາມໄຊ", "ຊານໄຊ", "ພູວົງ"],
    districts_en: ["Saysetha", "Samakkhixay", "Sanamxay", "Sanxay", "Phouvong"],
  },
  Bokeo: {
    key: "Bokeo",
    name_la: "ບໍ່ແກ້ວ",
    name_en: "Bokeo",
    districts_la: ["ຫ້ວຍຊາຍ", "ຕົ້ນເຜິ້ງ", "ເມິງ", "ຜາອຸດົມ", "ປາກທາ"],
    districts_en: ["Houayxay", "Ton Pheung", "Meung", "Pha Oudom", "Pak Tha"],
  },
  Bolikhamxai: {
    key: "Bolikhamxai",
    name_la: "ບໍລິຄຳໄຊ",
    name_en: "Bolikhamxai",
    districts_la: [
      "ປາກຊັນ",
      "ທ່າພະບາດ",
      "ປາກກະດິງ",
      "ບໍລິຄັນ",
      "ຄຳເກີດ",
      "ວຽງທອງ",
      "ໄຊຈຳພອນ",
    ],
    districts_en: [
      "Pakxan",
      "Thaphabat",
      "Pakkading",
      "Borikhane",
      "Khamkeut",
      "Viengthong",
      "Xaichamphon",
    ],
  },
  Champasak: {
    key: "Champasak",
    name_la: "ຈຳປາສັກ",
    name_en: "Champasak",
    districts_la: [
      "ປາກເຊ",
      "ຊະນະສົມບູນ",
      "ບາຈຽງຈະເລີນສຸກ",
      "ປາກຊ່ອງ",
      "ປະທຸມພອນ",
      "ໂພນທອງ",
      "ຈຳປາສັກ",
      "ສຸຂຸມາ",
      "ມູນລະປະໂມກ",
      "ໂຂງ",
    ],
    districts_en: [
      "Pakse",
      "Sanasomboun",
      "Batiengchaleunsouk",
      "Paksong",
      "Pathouphone",
      "Phonthong",
      "Champassack",
      "Soukhoumma",
      "Mounlapamok",
      "Khong",
    ],
  },
  Houaphanh: {
    key: "Houaphanh",
    name_la: "ຫົວພັນ",
    name_en: "Houaphanh",
    districts_la: [
      "ຊຳເໜືອ",
      "ຊຽງຄໍ້",
      "ວຽງທອງ",
      "ວຽງໄຊ",
      "ຫົວເມືອງ",
      "ຊຳໃຕ້",
      "ສົບເບົາ",
      "ແອດ",
    ],
    districts_en: [
      "Xam Neua",
      "Xiengkho",
      "Viengthong",
      "Viengxay",
      "Houameuang",
      "Samtay",
      "Sop Bao",
      "Et",
    ],
  },
  Khammouane: {
    key: "Khammouane",
    name_la: "ຄຳມ່ວນ",
    name_en: "Khammouane",
    districts_la: [
      "ທ່າແຂກ",
      "ມະຫາໄຊ",
      "ໜອງບົກ",
      "ຫີນບູນ",
      "ຍົມມະລາດ",
      "ບົວລະພາ",
      "ນາກາຍ",
      "ເຊບັ້ງໄຟ",
      "ໄຊບົວທອງ",
      "ຄູນຄຳ",
    ],
    districts_en: [
      "Thakhek",
      "Mahaxay",
      "Nong Bok",
      "Hineboun",
      "Yommalath",
      "Boualapha",
      "Nakai",
      "Sebangphay",
      "Xaibouathong",
      "Kounkham",
    ],
  },
  LuangNamTha: {
    key: "LuangNamTha",
    name_la: "ຫຼວງນ້ຳທາ",
    name_en: "Luang Namtha",
    districts_la: ["ຫຼວງນ້ຳທາ", "ສີງ", "ລອງ", "ວຽງພູຄາ", "ນາແລ"],
    districts_en: [
      "Luang Namtha",
      "Muang Sing",
      "Long",
      "Viengphoukha",
      "Na Le",
    ],
  },
  LuangPrabang: {
    key: "LuangPrabang",
    name_la: "ຫຼວງພະບາງ",
    name_en: "Luang Prabang",
    districts_la: [
      "ຫຼວງພະບາງ",
      "ຊຽງເງິນ",
      "ນານ",
      "ປາກອູ",
      "ນ້ຳບາກ",
      "ງອຍ",
      "ປາກແຊງ",
      "ໂພນໄຊ",
      "ຈອມເພັດ",
      "ວຽງຄຳ",
      "ພູຄູນ",
      "ໂພນທອງ",
    ],
    districts_en: [
      "Luang Prabang",
      "Xiengngeun",
      "Nane",
      "Pak Ou",
      "Nam Bak",
      "Ngoy",
      "Pak Seng",
      "Phonxay",
      "Chomphet",
      "Viengkham",
      "Phoukhoune",
      "Phonthong",
    ],
  },
  Oudomxay: {
    key: "Oudomxay",
    name_la: "ອຸດົມໄຊ",
    name_en: "Oudomxay",
    districts_la: ["ໄຊ", "ຫຼາ", "ນາໝໍ້", "ງາ", "ແບ່ງ", "ຮຸນ", "ປາກແບ່ງ"],
    districts_en: [
      "Xay",
      "La",
      "Namo",
      "Nga",
      "Beng",
      "Houne",
      "Pakbeng",
    ],
  },
  Phongsaly: {
    key: "Phongsaly",
    name_la: "ຜົ່ງສາລີ",
    name_en: "Phongsaly",
    districts_la: [
      "ຜົ້ງສາລີ",
      "ໃໝ່",
      "ຂວາ",
      "ສຳພັນ",
      "ບຸນເໜືອ",
      "ຍອດອູ",
      "ບຸນໃຕ້",
    ],
    districts_en: [
      "Phongsaly",
      "May",
      "Khoua",
      "Samphanh",
      "Boun Neua",
      "Yot Ou",
      "Boun Tay",
    ],
  },
  Salavan: {
    key: "Salavan",
    name_la: "ສາລະວັນ",
    name_en: "Salavan",
    districts_la: [
      "ສາລະວັນ",
      "ຕະໂອ້ຍ",
      "ຕຸ້ມລານ",
      "ລະຄອນເພັງ",
      "ວາປີ",
      "ຄົງເຊໂດນ",
      "ເລົ່າງາມ",
      "ສະມ້ວຍ",
    ],
    districts_en: [
      "Salavan",
      "Ta Oy",
      "Toumlane",
      "Lakhonepheng",
      "Vapy",
      "Khongsedone",
      "Lao Ngarm",
      "Sa Mouay",
    ],
  },
  Savannakhet: {
    key: "Savannakhet",
    name_la: "ສະຫວັນນະເຂດ",
    name_en: "Savannakhet",
    districts_la: [
      "ໄກສອນພົມວິຫານ",
      "ອຸທຸມພອນ",
      "ອາດສະພັງທອງ",
      "ພີນ",
      "ເຊໂປນ",
      "ນອງ",
      "ທ່າປາງທອງ",
      "ສອງຄອນ",
      "ຈຳພອນ",
      "ຊົນນະບູລີ",
      "ໄຊບູລີ",
      "ວິລະບູລີ",
      "ອາດສະພອນ",
      "ໄຊພູທອງ",
      "ພະລານໄຊ",
    ],
    districts_en: [
      "Kaysone Phomvihane",
      "Outhoumphone",
      "Atsaphangthong",
      "Phine",
      "Seponh",
      "Nong",
      "Thapangthong",
      "Songkhone",
      "Champhone",
      "Xonboury",
      "Xayboury",
      "Viraboury",
      "Assaphone",
      "Xayphouthong",
      "Thaphalanxay",
    ],
  },
  Vientiane: {
    key: "Vientiane",
    name_la: "ວຽງຈັນ",
    name_en: "Vientiane",
    districts_la: [
      "ໂພນໂຮງ",
      "ທຸລະຄົມ",
      "ແກ້ວອຸດົມ",
      "ກາສີ",
      "ວັງວຽງ",
      "ເຟືອງ",
      "ຊະນະຄາມ",
      "ແມດ",
      "ວຽງຄຳ",
      "ຫີນເຫີບ",
      "ໝື່ນ",
    ],
    districts_en: [
      "Phon Hong",
      "Thoulakhom",
      "Keo Oudom",
      "Kasy",
      "Vangvieng",
      "Feuang",
      "Xanakharm",
      "Mad",
      "Viengkham",
      "Hinhurp",
      "Meun",
    ],
  },
  VientianePrefecture: {
    key: "VientianePrefecture",
    name_la: "ນະຄອນຫຼວງວຽງຈັນ",
    name_en: "Vientiane Prefecture",
    districts_la: [
      "ຈັນທະບູລີ",
      "ສີໂຄດຕະບອງ",
      "ໄຊເສດຖາ",
      "ສີສັດຕະນາກ",
      "ນາຊາຍທອງ",
      "ໄຊທານີ",
      "ຫາດຊາຍຟອງ",
      "ສັງທອງ",
      "ປາກງື່ມ",
    ],
    districts_en: [
      "Chanthabouly",
      "Sikhottabong",
      "Xaysettha",
      "Sisattanak",
      "Naxaithong",
      "Xaythany",
      "Hadxaifong",
      "Sangthong",
      "Pak Ngum",
    ],
  },
  Sainyabuli: {
    key: "Sainyabuli",
    name_la: "ໄຊຍະບູລີ",
    name_en: "Sainyabuli",
    districts_la: [
      "ໄຊຍະບູລີ",
      "ຄອບ",
      "ຫົງສາ",
      "ເງິນ",
      "ຊຽງຮ່ອນ",
      "ພຽງ",
      "ປາກລາຍ",
      "ແກ່ນທ້າວ",
      "ບໍ່ແຕນ",
      "ທົ່ງມີໄຊ",
      "ໄຊສະຖານ",
    ],
    districts_en: [
      "Xayabury",
      "Khop",
      "Hongsa",
      "Ngeun",
      "Xienghone",
      "Phiang",
      "Parklai",
      "Kenethao",
      "Botene",
      "Thongmyxay",
      "Xaisathan",
    ],
  },
  Sekong: {
    key: "Sekong",
    name_la: "ເຊກອງ",
    name_en: "Sekong",
    districts_la: ["ລະມານ", "ກະລຶມ", "ດັກຈຶງ", "ທ່າແຕງ"],
    districts_en: [
      "La Mam",
      "Kaleum",
      "Dak Cheung",
      "Tha Teng",
    ],
  },
  Xaisomboun: {
    key: "Xaisomboun",
    name_la: "ໄຊສົມບູນ",
    name_en: "Xaisomboun",
    districts_la: ["ອະນຸວົງ", "ລ້ອງແຈ້ງ", "ລ້ອງຊານ", "ຮົ່ມ", "ທ່າໂທມ"],
    districts_en: [
      "Anouvong",
      "Longchaeng",
      "Longxan",
      "Hom",
      "Thathom",
    ],
  },
  Xiangkhouang: {
    key: "Xiangkhouang",
    name_la: "ຊຽງຂວາງ",
    name_en: "Xiangkhouang",
    districts_la: ["ແປກ", "ຄຳ", "ໜອງແຮດ", "ຄູນ", "ໝອກໃໝ່", "ພູກູດ", "ຜາໄຊ"],
    districts_en: [
      "Pek",
      "Kham",
      "Nong Het",
      "Khoune",
      "Mok May",
      "Phou Kout",
      "Phaxay",
    ],
  },
  // 📝 สามารถเติมให้ครบทั้ง 18 แขวงได้
};
