import type { Metadata } from "next";
import "./globals.css";
import { MessageProvider } from "@/components/frontend/context/MessageContext";
import ClientLayout from "@/components/frontend/appbar/ClientLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <MessageProvider>
          <ClientLayout>{children}</ClientLayout>
        </MessageProvider>
      </body>
    </html>
  );
}
