import type { Metadata } from "next";
import "./globals.css";
import { MessageProvider } from "@/components/frontend/context/MessageContext";
import { NotificationProvider } from "@/components/frontend/context/NotificationContext";
import ClientLayout from "@/components/frontend/appbar/ClientLayout";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {/* NotificationProvider ใส่ด้านบนสุด */}
        <NotificationProvider>
          <MessageProvider>
            <ClientLayout>
              {children}
              <Toaster richColors position="top-right" duration={2000} />
            </ClientLayout>
          </MessageProvider>
        </NotificationProvider>
      </body>
    </html>
  );
}
