import type { Metadata } from "next";
import "./globals.css";
import { MessageProvider } from "@/components/frontend/context/MessageContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <MessageProvider>{children}</MessageProvider>
      </body>
    </html>
  );
}
